import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("ecommerce video reuses the V2 canvas with product-sales defaults", () => {
  const shell = readFileSync(new URL("../AppShell.tsx", import.meta.url), "utf8");
  const canvas = readFileSync(new URL("./InfiniteCanvasWorkspace.tsx", import.meta.url), "utf8");
  const migration = readFileSync(new URL("../../../../../infra/migrations/134_commerce_creation_experience.up.sql", import.meta.url), "utf8");
  const audioMigration = readFileSync(new URL("../../../../../infra/migrations/135_ecommerce_video_audio_default.up.sql", import.meta.url), "utf8");
  const simpleDefaultsMigration = readFileSync(new URL("../../../../../infra/migrations/136_ecommerce_video_simple_defaults.up.sql", import.meta.url), "utf8");
  const compact = canvas.slice(canvas.indexOf("function EcommerceVideoCompact"), canvas.indexOf("function CanvasEditor"));
  const compactHeader = compact.slice(compact.indexOf("<header"), compact.indexOf("</header>"));
  assert.match(shell, /activeAgentCode === ECOMMERCE_VIDEO_CODE/);
  assert.match(shell, /workflowCode=\{ECOMMERCE_VIDEO_CODE\}[\s\S]*initialTemplateID="story-short-video-v2"/);
  assert.match(shell, /initialTemplateID="story-short-video-v2"[\s\S]*compactCommerce/, "commerce should show its lightweight shell instead of exposing the canvas by default");
  assert.match(canvas, /function EcommerceVideoCompact/);
  assert.match(compact, /<AgentLanding/, "commerce should reuse the same landing style as other agents");
  assert.match(compact, /absolute inset-0 z-30/, "the compact layer must stay below global workbench actions");
  assert.doesNotMatch(compactHeader, /帮助|专业编辑/, "help and professional editing do not belong in the page header");
  assert.match(compact, /relative z-10 shrink-0 px-3 pb-2 pt-1 sm:px-6 sm:pb-3/, "commerce video should reuse the system bottom-input container");
  assert.match(compact, /<ChatTopTools[\s\S]*自动创作[\s\S]*专业编辑[\s\S]*帮助/, "the shared asset library, creation mode and help belong on the upper input toolbar");
  assert.match(compact, /商品素材[\s\S]*<textarea[\s\S]*告诉 AI 你想做什么/, "product materials should appear before the inline prompt");
  assert.match(compact, /<textarea[\s\S]*发布平台与画幅[\s\S]*视频段数[\s\S]*声音与字幕[\s\S]*<ArrowUp/, "generation settings and submit arrow belong on the lower toolbar");
  assert.doesNotMatch(compact, /停止并保留已完成内容<\/|直接生成成片<\//, "the submit control should use an icon instead of a wide text button");
  assert.match(shell, /\(section === "agents" \|\| section === "gallery"\) && renderDesktopQuickActions\(\)/, "agents retain notification, language and user shortcuts");
  assert.match(canvas, /professionalView[\s\S]*right-4 top-16 z-50/, "return-to-simple must not cover global workbench actions");
  assert.match(canvas, /进入专业编辑/);
  assert.match(canvas, /返回简洁模式/);
  assert.match(canvas, /发布平台与画幅/);
  assert.match(canvas, /onFormatChange\(item\.platform, item\.aspectRatio\)/, "format menu must update real V2 settings");
  assert.match(canvas, /onSegmentCountChange\(count\)/, "segment menu must update real V2 settings");
  assert.match(canvas, /onAudioModeChange\(mode\)/, "audio menu must update real V2 settings");
  assert.match(canvas, /\{ targetDuration: count \* duration \}/, "segment changes must update the V2 target duration");
  assert.match(canvas, /useAudioModel: workspaceRuntime\.default_story_use_audio_model === true/);
  assert.match(canvas, /started && state\.canContinue \? ts\("继续生成"\)/, "an untouched task should say direct generation instead of continue");
  assert.match(canvas, /workspaceRuntime\.default_story_creation_type === "product" \? "product" : "story"/);
  assert.match(migration, /'default_story_creation_type', 'product'/);
  assert.match(migration, /'default_story_review_required', false/);
  assert.match(audioMigration, /'default_story_use_audio_model', true/);
  assert.match(migration, /'default_story_subtitle_mode', 'auto'/);
  assert.match(simpleDefaultsMigration, /'default_segment_count', 1/);
  assert.match(simpleDefaultsMigration, /'default_story_use_audio_model', false/);
  assert.match(simpleDefaultsMigration, /'default_story_subtitle_mode', 'none'/);
});
